version: "3.9"

# docker network create --gateway 173.21.1.1 --subnet 173.21.1.0/24 external-network

services:
  api:
    image: booking-api:latest
    hostname: api
    build: .
    ports:
      - "5106:80"
    networks:
      external-network:
        ipv4_address: 173.21.1.2
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: db
    ports:
      - "1433:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Password123456"
    networks:
      external-network:
        ipv4_address: 173.21.1.3

networks:
  global-network:
    driver: bridge
  external-network:
    external: true